version: "3.8"
services:
  user_ms:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run start
    ports:
      - "${SERVER_PORT}:3000"
    volumes:
      - .env:/.env
      - ./src:/src
      - ./package.json:/package.json
      - ./yarn.lock:/yarn.lock

volumes:
  mysql_volume:
    name: mysql-production-volume

networks:
  kiso_network:
    external: true